### ISSUE TITLE
Installation without cmake

### ISSUE THREAD

**Issue by poke1024** [foonathan/memory#100]
Hi there, this is a great project and it really feels like the standard part they missed shipping with the STL. I'm using this in a non-cmake project, so for the moment I prebuild everything and compile from prebuilt source artefacts. From what I can see the cmake step mainly does prepackaging however I got wary when I found the autogenerated `_impl.h` files. Are there any crucial platform dependent switches I'm missing and if so, could you point me to a location where platform dependent checks happen (e.g. custom platform std::list node size or stuff like that)? If not, all the better.

**Comment by poke1024** [comment]
...answering my own question, the correct answer is to switch my project build to cmake.

**Comment by foonathan** [comment]
The `config_impl.hpp` doesn't contain platform-specific switches, it just propagates various CMake options: https://github.com/foonathan/memory/blob/main/src/config.hpp.in

The other thing CMake does is invoke the tool to generate the node size information, if you can live without them you won't need it. Otherwise you can always run the tool yourself, see here how it is invoked: https://github.com/foonathan/memory/blob/main/src/CMakeLists.txt#L84
