### ISSUE TITLE
Is memory_pool_collection usable?

### ISSUE THREAD

**Issue by alexkh** [foonathan/memory#98]
Greetings!

I'm writing an html parser just for fun, and since the text of all elements can be of any size, I figured, it'd be nice to store them in a memory_pool_collection.

Unfortunately, this particular case is poorly documented, and I could not find a single example.

This trivial code segfaults:

```
#include <iostream>
#include <foonathan/memory/memory_pool_collection.hpp>

// alias namespace foonathan::memory as memory for easier access
#include <foonathan/memory/namespace_alias.hpp>

int main() {
	memory::memory_pool_collection<memory::node_pool, memory::log2_buckets,
		memory::heap_allocator> strings(4096, 32);

	std::cout << "Hello world" << std::endl;

	return 0;
}
```

**Comment by foonathan** [comment]
The allocator is the one with the least testing/benchmarking, yes, but it should be usable.

Your example segfaults because you need to swap the arguments: the first one is the maximal node size and the second one the block size. `(4096, 32)` means I want to allocate nodes up to 4096 bytes in size stored in contiguous blocks of size 32 - which doesn't work.
